import React from "react"
import "bootstrap/dist/css/bootstrap.min.css"
import Wrapper from "@/components/wrapper/Wrapper"
export const metadata = {
  title: 'InternshalaFrontend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <body>
        <Wrapper>
          {children}  
        </Wrapper>
      </body>
  )
}
